# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto_Attendance_GitHub_Action

on:
  workflow_dispatch:
  push:
  schedule:
    # 00:03 everyday in UTC+8, 16:03 everyday in UTC+0
    - cron: '03 16 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run app
        env:
          xxy_username: ${{ secrets.XXY_USERNAME }}
          xxy_password: ${{ secrets.XXY_PASSWORD }}
          zzw_username: ${{ secrets.ZZW_USERNAME }}
          zzw_password: ${{ secrets.ZZW_PASSWORD }}
        run: |
          python3 auto.py --username=$xxy_username --password=$xxy_password
          python3 auto.py --username=$zzw_username --password=$zzw_password
